### ISSUE TITLE
compgen breaks tabs/last-focused

### ISSUE THREAD

**Issue by buckley-w-david** [osnr/TabFS#14]
While poking around the file structure I noticed that the `tabs/last-focused` link stopped working at some point.

After reloading the extension and fiddling around a while I finally pined down that double tapping tab with something like `cat mnt/tabs/last-focused/` typed, triggering `compgen`, was what killed it.

To reproduce the issue:

1. Reload the extension
2. navigate to the `tabs` directory of the TabFS file system
```
[david@darvid-pc TabFS]$ cd fs/mnt/tabs
[david@darvid-pc tabs]$ ls -lah
total 0
drwxr-xr-x 3 root root   0 Dec 31  1969 .
drwxr-xr-x 3 root root   0 Dec 31  1969 ..
drwxr-xr-x 3 root root   0 Dec 31  1969 by-id
drwxrwxrwx 3 root root   0 Dec 31  1969 by-title
--w--w--w- 1 root root 100 Dec 31  1969 create
lr--r--r-- 1 root root   8 Dec 31  1969 last-focused -> by-id/6
[david@darvid-pc tabs]$ cat last-focused/url.txt
https://github.com/osnr/TabFS/issues/new
```
3. run compgen on the `last-focused` directory
```
[david@darvid-pc tabs]$ compgen -c last-focused/
last-focused/url.txt
last-focused/title.txt
last-focused/text.txt
last-focused/console
last-focused/execute-script
```
4. last-focused is now borked.
```
[david@darvid-pc tabs]$ ls -lah
total 0
drwxr-xr-x 3 root root   0 Dec 31  1969 .
drwxr-xr-x 3 root root   0 Dec 31  1969 ..
drwxr-xr-x 3 root root   0 Dec 31  1969 by-id
drwxrwxrwx 3 root root   0 Dec 31  1969 by-title
--w--w--w- 1 root root 100 Dec 31  1969 create
lr--r--r-- 1 root root   8 Dec 31  1969 last-focused -> by-id/6./windows/9
[david@darvid-pc tabs]$ cat last-focused/url.txt
cat: last-focused/url.txt: No such file or directory
```
Notice how `last-focused` now points to `by-id/6./windows/9`

I've had some inconsistent behavior, sometimes that "./" separating the `by-id/*` and `windows/*` isn't present, and it would just look like `by-id/6windows/9`

**Comment by csarven** [comment]
Experiencing similar in issue https://github.com/osnr/TabFS/issues/18 - not only for `last-focused`.
