### ISSUE TITLE
fzf doesn't operate under mnt/

### ISSUE THREAD

**Issue by jogloran** [osnr/TabFS#15]
Interestingly, [fzf, the fuzzy file finder](https://github.com/junegunn/fzf) doesn't work under `mnt/`. The directory appears empty, even though `find` returns results just fine.

**Comment by osnr** [comment]
Interesting. I wonder what system calls it's making -- you could maybe strace it and/or look at the extension console output when you run it

**Comment by jogloran** [comment]
I need to go through the rigmarole of disabling SIP to see for sure, but running dtruss on fzf while in `mnt/tabs/by-title` starts with the following output:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Comment by osnr** [comment]
This seems to work for me right now. It's possible that we were missing `.` or `..` somewhere back in January and it's since been added. Let me know if you have a chance to check this.

**Comment by jogloran** [comment]
It does work! Even though I was at `master` on TabFS, it seemed I needed to update `fzf` itself. 0.26.0 of `fzf` worked fine.
