### ISSUE TITLE
Opening Tabs?

### ISSUE THREAD

**Issue by JinchengWang** [osnr/TabFS#16]
~This is great for viewing and closing tabs, but could it support opening tabs as well?~
Is this what the create file is for? Would be great if this is documented.

**Comment by osnr** [comment]
yup: https://github.com/osnr/TabFS/blob/master/test/test.c#L44

yeah, I should document this when I have time -- or you're welcome to file a pull request also

**Comment by Helltux** [comment]
@osnr there is no create file in the window folder, is it possible to create new tabs in a specific window?

**Comment by Helltux** [comment]
i think i found the solution to this:
`Routes["/windows/#WINDOW_ID/crate"] = {
    async write({windowId, buf}) {
        const url = buf.trim();
        await browser.tabs.create({ windowId: windowId, url: url });
        return {size: stringToUtf8Array(buf).length};
    },
    async truncate() { return {}; }
}`
in the js file...

i will make later a PR, if i found out how...

**Comment by osnr** [comment]
Documented in #16 and deployed website to https://omar.website/tabfs/
