### ISSUE TITLE
Consider libferris support

### ISSUE THREAD

**Issue by zabbal** [osnr/TabFS#24]
The https://github.com/monkeyiq/ferris project seems to have very similar goals to the FUSE-side of TabFS, see http://www.libferris.com/features for details.

For instance, it might be simpler to generate xml on JS side and let libferris mount it as FUSE to avoid reimplementing stuff.

**Comment by osnr** [comment]
Thanks for the tip -- looks like a really cool project! they even had the idea of mounting Firefox 15 years ago. I bet we could learn a lot from them and find some cool abstractions and ideas for functionality to expose --

but I have to say that I don't think it's a good idea to replace our 200 lines of FUSE-side C with a giant C++ project (with a ton of extra dependencies).
