### ISSUE TITLE
Wrong program name?

### ISSUE THREAD

**Issue by gavinlaking** [osnr/TabFS#27]
Under the usage line there are instructions for `kill`?

![Screenshot_20210103_104618](https://user-images.githubusercontent.com/282423/103476878-4fe6ad80-4db1-11eb-9a88-15eff6b1edbd.png)

**Comment by osnr** [comment]
(I don't think this is an actual issue per se, since you're not supposed to be invoking `tabfs` from the command line by hand anyway -- it's meant for the browser to invoke. The usage for `kill` leaking out is a bit inelegant, though, so it'll be good when we get rid of it.)
