### ISSUE TITLE
Have usage of WebDriver instead of a custom extension been considered?

### ISSUE THREAD

**Issue by KOLANICH** [osnr/TabFS#28]
https://developer.mozilla.org/en-US/docs/Web/WebDriver

**Comment by osnr** [comment]
I spent a while looking up WebDriver just now, and… I still basically have no idea what it is or how the user experience or installation process works.

But I will say that these are some red lines I have, and it seems like WebDriver (or implementations of it, or whatever) may violate them:

- I prefer not to add any more dependencies (third-party client library, browser extension stub, programming languages that those are written in, dependencies they themselves have, etc).

- I prefer not to have extra abstraction layers between us and the browser. By using the extension APIs, we can do whatever the browser lets us do (can you even manage tabs and windows in WebDriver? it looks like it's meant for automation of an individual page. what about browser history? persistent storage?), we can fix anything that goes wrong ourselves, and we don't need to hack around limitations in tooling. (If we need to have special cases for Firefox or Safari, so be it -- I'd rather do that than involve an extra third-party layer)

- TabFS needs to work with the browser you already have running; it can't require that you start up the browser in a special mode, or use a headless browser, or anything like that.

**Comment by KOLANICH** [comment]
>TabFS needs to work with the browser you already have running; it can't require that you start up the browser in a special mode, or use a headless browser, or anything like that.

https://searchfox.org/mozilla-central/source/browser/app/winlauncher/LauncherProcessWin.cpp#89

Yeah, it requires to start a browser in a special mode. It can be done either by flags, or by env variables.

> (can you even manage tabs and windows in WebDriver? it looks like it's meant for automation of an individual page. what about browser history? persistent storage?)

To some extent. One can open and close tabs. About windows - I have not used this functionality, so IDK.

Marionette allows even more, since it is an internal protocol Mozilla used to test Firefox itself.

>I prefer not to add any more dependencies (third-party client library, browser extension stub, programming languages that those are written in, dependencies they themselves have, etc).

For Firefox the external dependency is an app starting Firefox in a certain mode (`--marionette` flag), setting up a temporary profile (damn damn damn slow and inefficient and making my system swap, but can be disabled) and translating between WebDriver and marionette. But one can use marionette protocol directly (it is a socket + JSON, the lib in rust implementing it is available), but this defeats the purpose of using WebDriver.

**Comment by osnr** [comment]
Thanks for the report. I'm going to close this for now, since I don't think we will adopt it, but I think this page will be a useful resource if this question comes up in future; appreciate you bringing it up.
