### ISSUE TITLE
Is it possible to add images shown in each tab to the FS?

### ISSUE THREAD

**Issue by the-oaks** [osnr/TabFS#3]
Is it possible to add images shown in each tab to fs?

**Comment by osnr** [comment]
hi! I think they should appear in the [`debugger/resources` subfolder](https://github.com/osnr/TabFS/blob/master/extension/background.js#L355) [already](https://twitter.com/rsnous/status/1344857885193322503), at least on Chrome. Let me know if you try it and run into any issues.
