### ISSUE TITLE
Question: can we have a shell script wrapper instead of system()?

### ISSUE THREAD

**Issue by 4z3** [osnr/TabFS#31]
Currently the `tabfs` executable is executing some simple shell script via `system()` before calling `fuse_main`. This makes it quite hard to extend because constructing strings in C can be annoying (to me at least ;)).  I've got [a commit on my fork](https://cgit.krebsco.de/TabFS/commit/?id=8a60517) that does all the shell stuff in `tabfs-wrapper` before executing the `tabfs` executable.  This makes it simple to e.g. [make the mountpoint configurable](https://cgit.krebsco.de/TabFS/commit/?id=5410f75).

My question is whether such a wrapper would be desirable to have in [this repo](https://github.com/osnr/TabFS).  If yes, then I would be delighted to create PR.

**Comment by osnr** [comment]
Hmm. I don't love the idea of a separate shell script wrapper, especially if we don't _need_ it -- in my view, more separate files (and languages) means more chances for stuff to get out of sight and go wrong.

I totally agree that a configurable mountpoint is a very good idea. I guess it could be done by setting it in an (optional) environment variable and then `getenv` in the C code and then `snprintf` to construct all the strings?

**Comment by osnr** [comment]
(I also want people to [feel comfortable](https://twitter.com/rsnous/status/1345113873792126976) investigating and editing the C code as much as they do the JS, even though it isn't generally that important to the fs functioning normally, and I think a shell script wrapper detracts from that a bit.)

**Comment by 4z3** [comment]
> I don't love the idea of a separate shell script wrapper

OK :+1:

> I guess it could be done [in C]

It can.  In fact, I've initially made the mountpoint configurable that way, but it didn't feel right to me to write shell in C, that's why I've replaced it by a wrapper in my repo which seemed to be a better tool for that task.
