### ISSUE TITLE
Configuring mount point instead of hardcoded "mnt" directory

### ISSUE THREAD

**Issue by buckley-w-david** [osnr/TabFS#37]
Checking to see if there is any interest from you (or others) for configuring the mount point instead of it being tied to a hardcoded `mnt` directory.

I've added a check for an environment variable `TABFS_MOUNT_DIR` to my fork, mostly curious if you'd like a PR for it.

You can check the diff here: https://github.com/osnr/TabFS/compare/master...buckley-w-david:master

**Comment by osnr** [comment]
Hi! Yes, this is great -- would definitely accept this PR. #31 shows that other people seem to want it, too.
