### ISSUE TITLE
request: support Brave Browser

### ISSUE THREAD

**Issue by phrohdoh** [osnr/TabFS#39]
[Brave](https://brave.com/) is a Chromium-based browser that, when reading the install script of this repo, doesn't appear to be supported.

I see [install documentation](https://omar.website/tabfs/#in-chrome-chromium-and-related-browsers) mentions passing `chrome` for Brave but the install script does not mention `"Brave Browser.app"`.

Of course, if Brave is already supported I'd be happy to see this ticket closed. :-)

**Comment by osnr** [comment]
I think it's already supported (#30) -- try it! I didn't want to add a half-dozen minor browsers to the second sentence of the writeup, but ideas on how to better represent this in the doc would be welcome...
