### ISSUE TITLE
Can't find TabFS chrome extension

### ISSUE THREAD

**Issue by tonylom3** [osnr/TabFS#41]
Hi folks. Looked everywhere in extension, Chrome Web Store, etc. Can't seem to locate the TabFS extension.

Thank you,
-Tony

**Comment by jtagcat** [comment]
https://omar.website/tabfs/#in-chrome-chromium-and-related-browsers

**Comment by tonylom3** [comment]
Clicking on the " Chrome extensions page" link on that page doesn't do anything, I realize it is supposed to take me to "chrome://extensions" but it doesn't.

Further, if I type "chrome://extensions" into the Chrome browser onmisearch - I don't see it listed as an extension even if I search. Could it be because of developer mode being on?

Last, if I go to the Chrome Web Store its not listed in the extensions there either.

Thank you,
-Tony

**Comment by tonylom3** [comment]
Meh, turned off dev mode. Made no difference.

-Tony

**Comment by jtagcat** [comment]
> Load-unpacked the extension/ folder in this repo.

You need to install/load the extension locally, manually, it is not available in the Google store.

**Comment by tonylom3** [comment]
Well ... almost got there. I get the following error. Restarted the extension, closed and reopened browser.

![browser_specific_settings](https://user-images.githubusercontent.com/11875810/104041842-a6842b00-51a7-11eb-92e7-f0bb9a78dff8.png)

**Comment by jtagcat** [comment]
The error is non-fatal. You may continue with the instructions at https://omar.website/tabfs/#2-install-the-c-filesystem
