### ISSUE TITLE
Focus on existing tab

### ISSUE THREAD

**Issue by enricozb** [osnr/TabFS#49]
Is there a way to focus on an existing tab?

**Comment by osnr** [comment]
I think you can `echo true > active`, but I haven't tried it: https://github.com/osnr/TabFS/blob/3c34988117236f0f2b11e773e9f5856adb039a45/extension/background.js#L349

(this might not bring the window to front, though…)

**Comment by jtagcat** [comment]
Manipulating windows isn't the doings of the browser, it won't.

**Comment by osnr** [comment]
I think we could potentially make `WINDOW/focused` that updates `chrome.windows.update(windowId, {focused}): https://developer.chrome.com/docs/extensions/reference/windows/#method-update but we don't have it right now.

**Comment by enricozb** [comment]
@osnr, your suggestion about `echo true > active` works. Thanks! Feel free to close this unless you want to keep it open for window focusing events.
