### ISSUE TITLE
Load temporary extension via bookmarklet in firefox?

### ISSUE THREAD

**Issue by LevProtter** [osnr/TabFS#54]
Anyone know if this is possible?

**Comment by bjesus** [comment]
AFAIK bookmarklets are only able to do what you're able to do anyway using JS in a page. So they shouldn't ever be allowed to load an extension, because that would mean any website could do the same.

**Comment by osnr** [comment]
I think that's right. If you want to keep the extension installed permanently, there are some answers in #4 for now (use dev edition and turn off signing requirement, or sign the extension yourself, I think)
