### ISSUE TITLE
get console messages

### ISSUE THREAD

**Issue by tfaureperso** [osnr/TabFS#56]
Hello thanks for this great tool.
What i want to do is some browser automation like with selenium. (But selenium are blocked by ddos cloudflare protection).

For example it's the ability to get some urls in a tab and to retrieve back then as text : for now i try to exec some JavaScript in the console to select the urls in a var and log it in the console
Is it possible to get/log console messages?

Is it the right way to do that?
Thanks in advance

**Comment by osnr** [comment]
Hi! you can look at (/ `tail -f`) `console`, although it's not that well-tested or documented: https://github.com/osnr/TabFS/blob/0a6c542c767f7cb13b577e4fb65af681a55c0aa8/test/test.c#L74
