### ISSUE TITLE
by-title symbolic links contain corrupted text

### ISSUE THREAD

**Issue by rareranger** [osnr/TabFS#7]
`ls -la Development/TabFS/fs/mnt/tabs/by-title`

total 0
drwxrwxrwx 3 root root  0 Jan  1  1970 .
drwxr-xr-x 3 root root  0 Jan  1  1970 ..
lr--r--r-- 1 root root 12 Jan  1  1970 Buffer___Node.js_v15.5.0_Documentation_62 -> ../by-id/62??V
lr--r--r-- 1 root root 12 Jan  1  1970 Extensions_22 -> ../by-id/22??V
lr--r--r-- 1 root root 12 Jan  1  1970 Issues___osnr_TabFS_51 -> ../by-id/51??V
lr--r--r-- 1 root root 12 Jan  1  1970 Syncthing_23 -> ../by-id/23??V

The text changes on each reload of the extension
`ls -la Development/TabFS/fs/mnt/tabs/by-title`
total 0
drwxrwxrwx 3 root root  0 Jan  1  1970 .
drwxr-xr-x 3 root root  0 Jan  1  1970 ..
lr--r--r-- 1 root root 12 Jan  1  1970 Buffer___Node.js_v15.5.0_Documentation_62 -> ../by-id/62y^U
lr--r--r-- 1 root root 12 Jan  1  1970 Extensions_22 -> ../by-id/22y^U
lr--r--r-- 1 root root 12 Jan  1  1970 New_Issue___osnr_TabFS_51 -> ../by-id/51y^U

**Comment by bjesus** [comment]
I'm seeing a similar behavior that I can't trace yet. See this tabs for example:
```
lr--r--r-- 1 root root 12 Jan  1  1970 WALKING_FAR_FROM_HOME_CHORDS__ver_2__by_Iron___Wine___Ultimate-Guitar.Com_75 -> ../by-id/757
lr--r--r-- 1 root root 12 Jan  1  1970 Walking___Psyche_Films_55 -> ../by-id/557
lr--r--r-- 1 root root 12 Jan  1  1970 WeChat_Is_Watching_-_Issue_73__Play_-_Nautilus_27 -> ../by-id/274
lr--r--r-- 1 root root 12 Jan  1  1970 What_Happened_When_I_Bought_A_Home_With_Sunrun_Solar_Panels_33 -> ../by-id/334
lr--r--r-- 1 root root 13 Jan  1  1970 XXXXXXXXXX_122 -> ../by-id/122
lr--r--r-- 1 root root 12 Jan  1  1970 What_I_ve_Learned_from_Hacker_News_22 -> ../by-id/224
lr--r--r-- 1 root root 13 Jan  1  1970 What_tools_are_best_for_animating_SVG_s____Designer_News_132 -> ../by-id/132
lr--r--r-- 1 root root 13 Jan  1  1970 xxxxxxxxxxxxx_101 -> ../by-id/101
lr--r--r-- 1 root root 13 Jan  1  1970 Workers___Account___Cloudflare_-_Web_Performance___Security_153 -> ../by-id/153
lr--r--r-- 1 root root 12 Jan  1  1970 Would_You_Recognize_a_Dystopia_If_You_Saw_One____The_Russell_Kirk_Center_34 -> ../by-id/344
lr--r--r-- 1 root root 12 Jan  1  1970 You_Don_t_Need_to_Quit_Your_Job_to_Make_32 -> ../by-id/324
lr--r--r-- 1 root root 11 Jan  1  1970 Calendar_-_January_2021_4 -> ../by-id/424
lr--r--r-- 1 root root 13 Jan  1  1970 XXXXXXXXXXXXXXXX_151 -> ../by-id/151
lr--r--r-- 1 root root 11 Jan  1  1970 Accounts_2 -> ../by-id/224
```

I masked some tab names.

Note how the last tab goes to `by-id/224` even though the tab id is `2`. Two tabs before it, it's tab `4` but goes to `424`. It looks like tab in between, 151, is already 3 characters so it doesn't get the additional `24`. The additional characters seem to change for me every now and then, as you can see the first two tabs on the list, 75 and 55, go to `757` and `557` (both don't exist).

I'm using Firefox Developer Edition on Arch.

**Comment by csarven** [comment]
Possibly related issue https://github.com/osnr/TabFS/issues/18

**Comment by curiosor** [comment]
is it an encoding problem? in my situation, a tab with title "微软 Bing 搜索 - 国际版" becomes "(underscore*3)Bing(underscore*4)-(underscore*5)"
direct copy-paste dosen't work here, because github comment filters out continuous underscores

**Comment by bjesus** [comment]
I think that what you're describing is just a sanitize function that removes special character. That seems to be by design.

**Comment by osnr** [comment]
Yeah, it sounds like this is just a C-side problem. I'm still looking at the pull requests that have come in.

(I think it would be a good idea to change the design of `sanitize` to be more tolerant and let characters in other languages through; what we have right now was just the first thing I thought to write. It only really needs to filter stuff like whitespace that is annoying on the shell, if it needs to exist at all. This might also require making sure all the encoding stuff for `readlink` is correct for all of UTF-8, which I haven't checked.)

**Comment by osnr** [comment]
@curiosor you may also be interested in #59 where folks have implemented some more tolerant sanitizers
