### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dflock** [osnr/TabFS#8]
I can't see a license for this project, currently?

**Comment by osnr** [comment]
It's GPLv3 (on the Web page). Pull request welcome if you want to add the license to background.js / tabfs.c / README.md also!

**Comment by LouisCAD** [comment]
@osnr I think you should leave this issue open until you add the proper license file, or merge someone submitting a PR faster than you. Otherwise, you'll probably keep getting duplicates like #23.
